site_url: https://thar-ai.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - { label: 'Biography', name: 'biography', widget: 'markdown', required: false }
          - { label: Site Email, name: siteemail, widget: string, required: false }
          - { label: Youtube, name: youtube, widget: string, required: false }
          - { label: Spotify, name: spotify, widget: string, required: false }
          - { label: Tidal, name: tidal, widget: string, required: false }
          - { label: Apple Music, name: appleMusic, widget: string, required: false }
          - { label: Instagram, name: instagram, widget: string, required: true }
          - { label: Facebook, name: facebook, widget: string, required: true }
  - name: 'discography'
    label: 'Discography'
    label_singular: 'Discography'
    folder: 'content/discography'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'discography/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Released at', name: 'releasedAt', widget: 'date', default: '', format: 'YYYY.MM.DD' }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  - name: 'lyrics'
    label: 'Lyrics'
    folder: 'content/lyrics'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Number', name: 'number', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - label: "Album"
        name: "album"
        widget: "relation"
        collection: "discography"
        value_field: "{{slug}}"
        search_fields: ['title']
